name: Deploy to staging or prod and test
concurrency: staging_environment
on:
  push:
    branches: [ main ]
env:
  terraform_version: '1.1.7'
  terraform_working_dir: 'fastly/terraform/'
  fastly_vcl_service_id: 2l7QhcR5rkdg691tcdRTD7
  fastly_compute_service_id: 4cUBTkiSVlJnR8JPnLvt85
  fastly_top_pops_config: 4dfSlimwvlJELO6htcnGsi
  fastly_compute_edge_config: 52hxZN9sNy7jyAdvvGKekc
  domain: qa.polyfill.io
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.1.0
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - name: Set cache-key
      id: cache-key
      run: echo "CACHE_KEY=compute-package-$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
    - name: Restore compute-package from cache
      uses: actions/cache@v3
      id: compute-package
      with:
        path: pkg/package.tar.gz
        key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    - if: steps.compute-package.outputs.cache-hit != 'true'
      uses: actions/setup-node@v3.1.0
      with:
        node-version: 18.x
        cache: 'npm'
    - if: steps.compute-package.outputs.cache-hit != 'true'
      run: npm ci
    - name: Set up Fastly CLI
      if: steps.compute-package.outputs.cache-hit != 'true'
      uses: fastly/compute-actions/setup@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        cli_version: '7.0.1'
    - if: steps.compute-package.outputs.cache-hit != 'true'
      run: fastly compute build --package-name package
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.cache-key.outputs.CACHE_KEY }}
        path: pkg/package.tar.gz
    - name: Remove the development and production terraform configuration overrides
      run: rm -f terraform.tfstate fastly/terraform/dev_override.tf fastly/terraform/production_override.tf fastly/terraform/domains_override.tf
    - uses: ./.github/actions/terraform
      with:
        fastly-api-token: ${{ secrets.FASTLY_API_KEY }}
        fastly_vcl_service_id: ${{ env.fastly_vcl_service_id }}
        fastly_compute_service_id: ${{ env.fastly_compute_service_id }}
        fastly_top_pops_config: ${{ env.fastly_top_pops_config }}
        fastly_compute_edge_config: ${{ env.fastly_compute_edge_config }}

  end-to-end-test:
    needs: [deploy-to-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test:integration
        env:
          HOST: "https://${{ env.domain }}"
